stages:
  - lint
  - test
  - build
  - release

lint:
  stage: lint
  image: python:3.12-bookworm
  before_script:
    - python3 -m pip install --no-cache-dir -U pip pipenv
    - python3 -m pipenv install --dev --deploy --system
  script:
    - python3 -m ruff format --no-cache --check .
  except:
    - tags

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml


build:
  stage: build
  image: python:3.12-bookworm
  only:
    - tags
  before_script:
    - python3 -m pip install -U pip build
  script:
    - sed -i "s/__VERSION__/$CI_COMMIT_TAG/g" pyproject.toml
    - find . -type f -name '*.py' -exec sed -i "s/__VERSION__/$CI_COMMIT_TAG/g" {} +
    - python -m build --outdir dist .
  artifacts:
    paths:
      - dist/*

release:
  stage: release
  environment:
    name: release
  image: python:3.12-bookworm
  only:
    - tags
  id_tokens:
    PYPI_ID_TOKEN:
      aud: pypi
  before_script:
    - apt update && apt install -y jq
    - python3 -m pip install -U twine id
  script:
    - oidc_token=$(python -m id PYPI)
    - resp=$(curl -X POST https://pypi.org/_/oidc/mint-token -d "{\"token\":\"${oidc_token}\"}")
    - api_token=$(jq --raw-output '.token' <<< "${resp}")
    - twine check dist/*
    - twine upload --repository pypi -u __token__ -p "${api_token}" dist/*